# Site Settings
title: My Resume
url: 'https://danielnguyen,github.io'
baseurl: '/' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Daniel Nguyen
tagline: Full Stack Developer and Team Lead
pic: daniel-nguyen.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: '<ul>
<li>Self-motivated to achieve peak performance and meet business objectives.</li>
<li>Ability to propose and create solutions from proposal through implementation.</li>
<li>Ability to troubleshoot and identify potential problems and provide solutions.</li>
<li>Collaborate well in teams but can work well individually.</li>
<li>Possess excellent customer facing skills, with the ability to communicate effectively.</li>
</ul>'

#sidebar links
# email: hello@webjeda.com
# phone: 012 345 6789
website: danielnguyen.github.io
linkedin: danielnguyenhuu
github: danielnguyen
#Update all the sections by editing the files inside _data folder.

# Tracker
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
